app/home/forms.py
#coding:utf8
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, FileField, TextAreaField, SelectField, SelectMultipleField
from wtforms.validators import DataRequired, ValidationError, EqualTo, Email, Regexp

from app.models import User


class RegisterForm(FlaskForm):
    """
    会员登陆表单
    """
    name = StringField(
        label='昵称',
        validators=[
            DataRequired('请输入昵称')
        ],
        description='昵称',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '请输入昵称',
        }
    )
    email = StringField(
        label='邮箱',
        validators=[
            DataRequired('请输入邮箱'),
            Email('邮箱格式不正确')
        ],
        description='邮箱',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '请输入邮箱',
        }
    )
    phone = StringField(
        label='手机号',
        validators=[
            DataRequired('请输入手机号'),
            Regexp('1[3458]\\d{9}', message='手机号格式不正确')
        ],
        description='手机号',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '请输入手机号',
        }
    )
    pwd = PasswordField(
        label='密码',
        validators=[
            DataRequired('请输入密码')
        ],
        description='密码',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '请输入密码',
            # 'required': 'required'
        }
    )
    re_pwd = PasswordField(
        label='再次输入密码',
        validators=[
            DataRequired('请再次输入密码'),
            EqualTo('pwd', message='两次密码不一致')
        ],
        description='再次输入密码',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '请再次输入密码',
        }
    )
    submit = SubmitField(
        '注册',
        render_kw={
            'class': 'btn btn-lg btn-success btn-block',
        }
    )

    def validate_name(self, field):
        name = field.data
        user = User.query.filter_by(name=name).count()
        if user == 1:
            raise ValidationError('昵称已经被注册')

    def validate_email(self, field):
        email = field.data
        user = User.query.filter_by(email=email).count()
        if user == 1:
            raise ValidationError('邮箱已经被注册')

    def validate_phone(self, field):
        phone = field.data
        user = User.query.filter_by(phone=phone).count()
        if user == 1:
            raise ValidationError('手机号已经被注册')


class LoginForm(FlaskForm):
    """
    注册表单
    """
    name = StringField(
        label='账号',
        validators=[
            DataRequired('请输入账号')
        ],
        description='账号',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '请输入账号',
        }
    )
    pwd = PasswordField(
        label='密码',
        validators=[
            DataRequired('请输入密码')
        ],
        description='密码',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '请输入密码',
            # 'required': 'required'
        }
    )
    submit = SubmitField(
        '登陆',
        render_kw={
            'class': 'btn btn-lg btn-success btn-block',
        }
    )


class UserDetailForm(FlaskForm):
    """
    用户详细信息表单
    """
    name = StringField(
        label='昵称',
        validators=[
            DataRequired('请输入昵称')
        ],
        description='昵称',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入昵称',
        }
    )
    email = StringField(
        label='邮箱',
        validators=[
            DataRequired('请输入邮箱'),
            Email('邮箱格式不正确')
        ],
        description='邮箱',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入邮箱',
        }
    )
    phone = StringField(
        label='手机号',
        validators=[
            DataRequired('请输入手机号'),
            Regexp('1[3458]\\d{9}', message='手机号格式不正确')
        ],
        description='手机号',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入手机号',
        }
    )
    image = FileField(
        label='头像',
        validators=[
            DataRequired('请上传头像'),
        ],
        description='头像'
    )
    info = TextAreaField(
        label='简介',
        validators=[
            DataRequired('请输入简介')
        ],
        description='简介',
        render_kw={
            'class': 'form-control',
            'row': 10,
        }
    )
    submit = SubmitField(
        '保存修改',
        render_kw={
            'class': 'btn btn-lg btn-success btn-block',
        }
    )


class PWDResetForm(FlaskForm):
    """
    修改密码表单
    """
    old_pwd = PasswordField(
        label='旧密码',
        validators=[
            DataRequired('请输入旧密码')
        ],
        description='旧密码',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入旧密码',
        }
    )
    new_pwd = PasswordField(
        label='新密码',
        validators=[
            DataRequired('请输入新密码')
        ],
        description='新密码',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入新密码',
        }
    )
    submit = SubmitField(
        '修改密码',
        render_kw={
            'class': 'btn btn-primary',
        }
    )


class CommentForm(FlaskForm):
    content = TextAreaField(
        label='评论',
        validators=[
            DataRequired('请输入评论')
        ],
        description='内容',
        render_kw={
            'id': 'input_content'
        }

    )

    submit = SubmitField(
        '提交评论',
        render_kw={
            'class': "btn btn-success",
            'id': "btn-sub"
        }
    )

app/home/__init__.py
# coding:utf8
from flask import Blueprint

home = Blueprint('home', __name__)

import app.home.views

app/home/views.py
# coding:utf8
from flask import render_template, redirect, url_for, flash, session, request, Response
from werkzeug.security import generate_password_hash
from functools import wraps
from werkzeug.utils import secure_filename
import uuid
import os
import datetime
import stat
import json

from . import home
from .forms import RegisterForm, LoginForm, UserDetailForm, PWDResetForm, CommentForm
from app.models import User, UserLog, MoviePreview, Tag, Movie, Comment, MovieCollection
from app import db, app, redis


def change_filename(filename):
    """
    生成一个唯一的文件名
    """
    # 将文件名和后缀分离
    file_info = os.path.splitext(filename)
    # 文件名为：添加时间+uuid生成的唯一字符串+文件后缀
    filename = datetime.datetime.now().strftime('%Y%m%d%H%M%S') + str(uuid.uuid4().hex) + file_info[1]
    return filename


def user_login_req(f):
    """
    登陆访问装饰器
    """
    @wraps(f)
    def decorated_function(*args, **kwargs):
        #  未登陆的话重定向到登陆页面
        if 'user' not in session:
            return redirect(url_for('home.login', next=request.url))
        return f(*args, **kwargs)
    return decorated_function


@home.route('/<int:page>/', methods=['GET'])
def index(page=None):
    """"
    首页
    """
    tags = Tag.query.all()
    tag_id = request.args.get('tag_id', 0)
    star = request.args.get('star', 0)
    time = request.args.get('time', 0)
    pm = request.args.get('pm', 0)
    cm = request.args.get('cm', 0)

    data = Movie.query
    if int(tag_id) != 0:
        # 按照tag筛选
        data = data.filter_by(tag_id=tag_id)

    if int(star) != 0:
        # 按照星级筛选
        data = data.filter_by(star=int(star))

    if int(time) != 0:
        if int(time) == 1:  # 时间早到晚
            data = data.order_by(Movie.add_time.desc())
        if int(time) == 2:  # 时间晚到早
            data = data.order_by(Movie.add_time.asc())

    if int(pm) != 0:
        if int(pm) == 1:  # 播放量高到低
            data = data.order_by(Movie.play_num.desc())
        if int(pm) == 2:  # 播放量低到高
            data = data.order_by(Movie.play_num.asc())

    if int(cm) != 0:
        if int(cm) == 1:  # 评论量高到低
            data = data.order_by(Movie.comment_num.desc())
        if int(cm) == 2:  # 评论量低到高
            data = data.order_by(Movie.comment_num.asc())

    if page is None:
        page = 1
    data = data.paginate(page=page, per_page=8)
    p = dict(
        tag_id=tag_id,
        star=star,
        time=time,
        pm=pm,
        cm=cm
    )
    return render_template('home/index.html', tags=tags, p=p, data=data)


@home.route('/login/', methods=['GET', 'POST'])
def login():
    """"
    登陆
    """
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=data['name']).first()
        if not user.check_pwd(data['pwd']):
            flash('密码错误', 'error')
            return redirect(url_for('home.login'))
        # 保存用户信息到session中
        session['user'] = user.name
        session['user_id'] = user.id

        # 记录会员登陆
        user_log = UserLog(
            user_id=user.id,
            login_ip=request.remote_addr
        )
        db.session.add(user_log)
        db.session.commit()
        return redirect(url_for('home.user_center'))
    return render_template('home/login.html', form=form)


@home.route('/logout/')
def logout():
    """"
    登出
    """
    session.pop('user', None)
    session.pop('user_id', None)
    return redirect(url_for('home.login'))


@home.route('/register/', methods=['GET', 'POST'])
def register():
    """"
    注册
    """
    form = RegisterForm()
    if form.validate_on_submit():
        data = form.data
        user = User(
            name=data['name'],
            email=data['email'],
            phone=data['phone'],
            pwd=generate_password_hash(data['pwd']),
            uuid=uuid.uuid4().hex
        )
        db.session.add(user)
        db.session.commit()
        flash('注册成功，请登陆', 'success')
        return redirect(url_for('home.login'))
    return render_template('home/register.html', form=form)


@home.route('/user_center/', methods=['GET', 'POST'])
@user_login_req
def user_center():
    """"
    用户中心
    """
    form = UserDetailForm()
    form.image.validators = []
    user = User.query.get(int(session['user_id']))

    # 赋值
    if request.method == 'GET':
        form.name.data = user.name
        form.email.data = user.email
        form.phone.data = user.phone
        form.info.data = user.info

    if form.validate_on_submit():
        data = form.data
        print(form.image.data)
        # 保存头像
        file_image = secure_filename(form.image.data.filename)
        if not os.path.exists(app.config['USER_IMAGE_DIR']):
            os.makedirs(app.config['USER_IMAGE_DIR'])
            os.chmod(app.config['USER_IMAGE_DIR'], stat.S_IRWXU)
        user.image = change_filename(file_image)
        form.image.data.save(app.config['USER_IMAGE_DIR'] + user.image)

        # 剩余信息录入
        user.name = data['name']
        user.email = data['email']
        user.phone = data['phone']
        user.info = data['info']
        db.session.add(user)
        db.session.commit()
        flash('修改成功', 'success')
        return redirect(url_for('home.user_center'))
    return render_template('home/user_center.html', form=form, user=user)


@home.route('/pwd_reset/', methods=['GET', 'POST'])
@user_login_req
def pwd_reset():
    """"
    密码重置
    """
    form = PWDResetForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=session['user']).first()

        if not user.check_pwd(data['old_pwd']):
            flash('旧密码错误', 'error')
            return redirect(url_for('home.pwd_reset'))
        user.pwd = generate_password_hash(data['new_pwd'])
        db.session.add(user)
        db.session.commit()
        flash('修改密码成功，请重新登陆', 'success')
        return redirect(url_for('home.logout'))
    return render_template('home/pwd_reset.html', form=form)


@home.route('/my_comment/<int:page>/')
@user_login_req
def my_comment(page=None):
    """"
    我的评论
    """
    if page is None:
        page = 1
    data = Comment.query.join(Movie).filter(
        Comment.movie_id == Movie.id,
        Comment.user_id == session['user_id']
    ).order_by(Comment.add_time.desc()).paginate(page=page, per_page=3)
    return render_template('home/my_comment.html', data=data)


@home.route('/login_log/<int:page>/', methods=['GET'])
@user_login_req
def login_log(page=None):
    """"
    我的登录日志
    """
    if page is None:
        page = 1
    # 关联User表
    data = UserLog.query.filter_by(
        user_id=int(session['user_id'])
    ).order_by(
        UserLog.login_time.desc()
    ).paginate(page=page, per_page=2)
    return render_template('home/login_log.html', data=data)


@home.route('/movie_fav/add/', methods=['GET', 'POST'])
@user_login_req
def movie_fav():
    """"
    收藏电影
    """
    user_id = request.args.get('user_id', '')
    movie_id = request.args.get('movie_id', '')
    movie_col_count = MovieCollection.query.filter_by(
        user_id=int(user_id),
        movie_id=int(movie_id)
    ).count()

    if movie_col_count == 1:  # 已收藏，进行取消收藏操作
        movie_col = MovieCollection.query.filter_by(
            user_id=int(user_id),
            movie_id=int(movie_id)
        ).first_or_404()
        db.session.delete(movie_col)
        db.session.commit()
        data = dict(ok=0)

    if movie_col_count == 0:  # 未收藏, 进行收藏操作
        movie_col = MovieCollection(
            user_id=int(user_id),
            movie_id=int(movie_id)
        )
        db.session.add(movie_col)
        db.session.commit()
        data = dict(ok=1)
    return json.dumps(data)


@home.route('/movie_col_list/<int:page>/', methods=['GET'])
@user_login_req
def movie_col_list(page=None):
    """
    我收藏的电影
    """
    if page is None:
        page = 1

    data = MovieCollection.query.join(Movie).join(User).filter(
        User.id == session['user_id'],
        Movie.id == MovieCollection.movie_id
    ).order_by(MovieCollection.add_time.desc()).paginate(page=page, per_page=4)

    return render_template('home/movie_col_list.html', data=data)


@home.route('/animation/')
def animation():
    """"
    首页动画
    """
    data = MoviePreview.query.all()
    return render_template('home/animation.html', data=data)


@home.route('/search/<int:page>/', methods=['GET'])
def search(page=None):
    """"
    搜索
    """
    key = request.args.get('key', '')

    # 搜索到的电影数
    movie_count = Movie.query.filter(
        Movie.title.ilike('%' + key + '%')
    ).count()

    data = Movie.query.filter(
        Movie.title.ilike('%' + key + '%')
    ).order_by(
        Movie.add_time.desc()
    ).paginate(page=page, per_page=4)
    return render_template('home/search.html', key=key, data=data, movie_count=movie_count)


@home.route('/play/<int:id>/<int:page>/', methods=['GET', 'POST'])
def play(id=None, page=None):
    """"
    播放
    """
    # 电影是否被收藏标志
    has_fav = False

    if 'user' in session:
        count = MovieCollection.query.filter_by(
            user_id=session['user_id'],
            movie_id=int(id)
        ).count()

        # 判断该电影时候已被收藏
        if count == 0:
            has_fav = False
        else:
            has_fav = True

    form = CommentForm()

    # 电影实体
    movie = Movie.query.join(Tag).filter(
        Tag.id == Movie.tag_id,
        Movie.id == int(id)
    ).first_or_404()

    # 电影评论
    if page is None:
        page = 1
    # 关联Movie和User表
    data = Comment.query.join(Movie).join(User).filter(
        Movie.id == movie.id,
        User.id == Comment.user_id,
    ).order_by(
        Comment.add_time.desc()
    ).paginate(page=page, per_page=4)

    # 点进来播放量+1
    movie.play_num += 1

    # 评论提交
    if 'user' in session and form.validate_on_submit():
        data = form.data
        comment = Comment(
            content=data['content'],
            movie_id=int(id),
            user_id=session['user_id']
        )

        db.session.add(comment)

app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/animate.css') }}">
    <style>
        .navbar-brand>img {
        }
        .media{
            padding:3px;
            border:1px solid #ccc
        }
    </style>
    {% block css %}{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index', page=1) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static', filename='base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" id="movie_search">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="search"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index', page=1) }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register') }}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.user_center') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}{% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static', filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static', filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });

    $('#search').click(function () {
            var key = $('#movie_search').val();
            location.href = '{{ url_for('home.search', page=1) }}?key=' + key
        });
    });

</script>
{% block js %}{% endblock %}
</body>
</html>

app/templates/home/layout.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/animate.css') }}">
    <style>
        .navbar-brand>img {
            display: inline;
        }
        .media{
            padding:3px;
            border:1px solid #ccc
        }
    </style>
    {% block css %}{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index', page=1) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static', filename='base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" id="movie_search">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="search"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index', page=1) }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register') }}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.user_center') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
    {% block content %}{% endblock %}
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static', filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static', filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    $('#search').click(function () {
            var key = $('#movie_search').val();
            location.href = '{{ url_for('home.search', page=1) }}?key=' + key
        });
    });

</script>
{% block js %}{% endblock %}
</body>
</html>

app/templates/home/menu.html
<div class="col-md-3">
    <div class="list-group">
        <a id="user_center" href="{{ url_for('home.user_center') }}" class="list-group-item">
            <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
        </a>
         <a id='pwd_reset' href="{{ url_for('home.pwd_reset') }}" class="list-group-item">
            <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
        </a>
        <a id='my_comment' href="{{ url_for('home.my_comment', page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
        </a>
        <a id='login_log' href="{{ url_for('home.login_log', page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
        </a>
        <a id='movie_fav' href="{{ url_for('home.movie_col_list', page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
        </a>
    </div>
</div>

app/templates/home/movie_col_list.html
{% extends 'home/home.html' %}
{% import 'ui/admin_page.html' as pg %}

{% block css %}
    <style>
        .col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9{
            padding-right: 3px;
            padding-left: 3px;
        }
    </style>
{% endblock %}

{% block content %}
    {% include 'home/menu.html' %}
    <div class="col-md-9">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;收藏电影</h3>
            </div>
            <div class="panel-body">
                <div class="col-md-12">
                    {% for item in data.items %}
                    <div class="media">
                        <div class="media-left">
                            <a href="{{ url_for('home.dmplay', id=item.movie_id, page=1) }}">
                                <img style="width: 400px;height: 300px;" class="media-object" src="{{ url_for('static', filename='uploads/'+item.movie.logo) }}" alt="{{ item.movie.title }}">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">{{ item.movie.title }}<a href="{{ url_for('home.play', id=item.movie_id, page=1) }}" class="label label-primary pull-right"><span class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                            {{ item.movie.info }}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="col-md-12 text-center" style="margin-top:6px;">
                    <nav aria-label="Page navigation">
                         {{ pg.page(data, 'home.movie_col_list') }}
                    </nav>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
           $('#movie_fav').addClass('active');
        });
    </script>
{% endblock %}